Partimos de lo que hicimos en el notebook anterior para trabajar con las columnas de datos numéricos. 

Primero vamos a cargarlo nuevamente.

In [3]:
import numpy as np
import pandas as pd

filename = 'datasets/dataframe_clase_3_limpio.csv'
df = pd.read_csv(filename)
df

    Unnamed: 0  Edad  Altura   Peso  Promedio Sexo      LU     Observación
0            0    25    1.80   83.0      7.79    h  125/89          ninguna
1            1    21    1.89   86.0      9.70    h   35/88          ninguna
2            2    39    1.54   50.0      7.10    m  142/80     hipertension
3            3    49    1.66   70.0      6.54    m  553/83          ninguna
4            4    31    1.70   81.0      7.21    h  495/83     hipertension
5            5    33    1.74   93.0      7.10    h   25/78          ninguna
6            6    29    1.81   82.5      6.90    h  445/81          ninguna
7            7    19    1.82   86.3      8.43    h    5/84          ninguna
8            8    20    1.76   75.0     10.00    m    1/81          ninguna
9           10    32    1.64   60.0      9.10    m  400/80          ninguna
10          11    59    1.70   67.0      8.99   nb  100/89          ninguna
11          12    34    1.81   97.0      7.46    h    1/89          ninguna
12          13    49    1.78  432.0      7.41    h  500/86  dolor de cabeza
13          14    51    1.77   75.0      9.10    h   25/85     hipertension
14          17    41    1.80    8.0      9.20    h  099/89          ninguna
15          19    28    1.68   68.0      7.54    m  145/81          ninguna

En la clase vimos que hay distintas formas de remover outliers. En este caso, la columna peso tiene un outliner bastante claro que tiene sentido remover (índice 12), es más, podemos sospechar que alguien se equivocó cuando ingresó los datos. Hubiese pasado algo similar si encontrabamos alguien con edad -4 o 221 años. 

En este caso no vamos a remover datos usando criterios basados en el desvío estándar, aunque sería similar el procedimiento.

In [9]:
indice = df[np.logical_or(df['Peso']>400, df['Peso']<10)].index  # el indice donde esta la fila con un peso mayor a 400
df_1 = df.drop(indice)
df_1

    Unnamed: 0  Edad  Altura  Peso  Promedio Sexo      LU  Observación
0            0    25    1.80  83.0      7.79    h  125/89       ninguna
1            1    21    1.89  86.0      9.70    h   35/88       ninguna
2            2    39    1.54  50.0      7.10    m  142/80  hipertension
3            3    49    1.66  70.0      6.54    m  553/83       ninguna
4            4    31    1.70  81.0      7.21    h  495/83  hipertension
5            5    33    1.74  93.0      7.10    h   25/78       ninguna
6            6    29    1.81  82.5      6.90    h  445/81       ninguna
7            7    19    1.82  86.3      8.43    h    5/84       ninguna
8            8    20    1.76  75.0     10.00    m    1/81       ninguna
9           10    32    1.64  60.0      9.10    m  400/80       ninguna
10          11    59    1.70  67.0      8.99   nb  100/89       ninguna
11          12    34    1.81  97.0      7.46    h    1/89       ninguna
13          14    51    1.77  75.0      9.10    h   25/85  hipertension
15          19    28    1.68  68.0      7.54    m  145/81       ninguna

Ahora pensamos como estandarizar las columnas. Supongamos que no hay diferencias en la edad típica en la que se matriculan estudiantes a la Universidad. Entonces tiene sentido hablar del desvío de la media, en unidades de desvío estandar. Es decir, podemos transformar la columna "Edad" a z-scores:

In [32]:
from scipy.stats import zscore
df_1['Edad'] = zscore(df_1['Edad'])
df_1

,Unnamed: 0,Edad,Altura,Peso,Promedio,Sexo,LU,Observación,Edad (z),Altura (z)
0,0,-0.734333,1.80,83.0,7.79,h,125/89,ninguna,-0.734333,0.140642
1,1,-1.077022,1.89,86.0,9.70,h,35/88,ninguna,-1.077022,1.828348
2,2,0.465078,1.54,50.0,7.10,m,142/80,hipertension,0.465078,-1.636565
3,3,1.321800,1.66,70.0,6.54,m,553/83,ninguna,1.321800,0.056433
4,4,-0.220300,1.70,81.0,7.21,h,495/83,hipertension,-0.220300,-1.734587
5,5,-0.048956,1.74,93.0,7.10,h,25/78,ninguna,-0.048956,-0.984495
6,6,-0.391644,1.81,82.5,6.90,h,445/81,ninguna,-0.391644,0.328165
7,7,-1.248366,1.82,86.3,8.43,h,5/84,ninguna,-1.248366,0.515688
8,8,-1.162694,1.76,75.0,10.00,m,1/81,ninguna,-1.162694,1.467265
9,10,-0.134628,1.64,60.0,9.10,m,400/80,ninguna,-0.134628,-0.225733
10,11,2.178521,1.70,67.0,8.99,nb,100/89,ninguna,2.178521,0.590000
11,12,0.036717,1.81,97.0,7.46,h,1/89,ninguna,0.036717,0.328165
13,14,1.493144,1.77,75.0,9.10,h,25/85,hipertension,1.493144,-0.421927
15,19,-0.477316,1.68,68.0,7.54,m,145/81,ninguna,-0.477316,0.338600

¿Tiene sentido hacer lo mismo para la altura y el peso?

La altura y el peso tienden a ser mayores en hombres que en mujeres. Tendría sentido normalizar cada uno por la media el desvío estandar de su población. O bien usar un método de normalización que no compare con el desvío estándar, por ejemplo, normalización min-max.

Veamos ambos casos. Primero, z-score específico para cada grupo, computado para la altura.

In [33]:

indice_h = df_1['Sexo']=='h'
indice_m = df_1['Sexo']=='m'

df_1['Altura'] = np.zeros(len(df_1))  # ponemos 0 para despues poder modificarla
print(df_1)
df_1['Altura'][indice_h] = sp.stats.zscore(df_1['Altura'][indice_h])
print(df_1)
df_1['Altura'][indice_m] = sp.stats.zscore(df_1['Altura'][indice_m])
print(df_1)

    Unnamed: 0      Edad  Altura  Peso  Promedio Sexo      LU  Observación   \
0            0 -0.734333     0.0  83.0      7.79    h  125/89       ninguna
1            1 -1.077022     0.0  86.0      9.70    h   35/88       ninguna
2            2  0.465078     0.0  50.0      7.10    m  142/80  hipertension
3            3  1.321800     0.0  70.0      6.54    m  553/83       ninguna
4            4 -0.220300     0.0  81.0      7.21    h  495/83  hipertension
5            5 -0.048956     0.0  93.0      7.10    h   25/78       ninguna
6            6 -0.391644     0.0  82.5      6.90    h  445/81       ninguna
7            7 -1.248366     0.0  86.3      8.43    h    5/84       ninguna
8            8 -1.162694     0.0  75.0     10.00    m    1/81       ninguna
9           10 -0.134628     0.0  60.0      9.10    m  400/80       ninguna
10          11  2.178521     0.0  67.0      8.99   nb  100/89       ninguna
11          12  0.036717     0.0  97.0      7.46    h    1/89       ninguna
13          14  1.493144     0.0  75.0      9.10    h   25/85  hipertension
15          19 -0.477316     0.0  68.0      7.54    m  145/81       ninguna

    Edad (z)  Altura (z)
0  -0.734333    0.140642
1  -1.077022    1.828348
2   0.465078   -1.636565
3   1.321800    0.056433
4  -0.220300   -1.734587
5  -0.048956   -0.984495
6  -0.391644    0.328165
7  -1.248366    0.515688
8  -1.162694    1.467265
9  -0.134628   -0.225733
10  2.178521    0.590000
11  0.036717    0.328165
13  1.493144   -0.421927
15 -0.477316    0.338600
    Unnamed: 0      Edad  Altura  Peso  Promedio Sexo      LU  Observación   \
0            0 -0.734333     NaN  83.0      7.79    h  125/89       ninguna
1            1 -1.077022     NaN  86.0      9.70    h   35/88       ninguna
2            2  0.465078     0.0  50.0      7.10    m  142/80  hipertension
3            3  1.321800     0.0  70.0      6.54    m  553/83       ninguna
4            4 -0.220300     NaN  81.0      7.21    h  495/83  hipertension
5            5 -0.048956     NaN  93.0      7.10    h   25/78       ninguna
6            6 -0.391644     NaN  82.5      6.90    h  445/81       ninguna
7            7 -1.248366     NaN  86.3      8.43    h    5/84       ninguna
8            8 -1.162694     0.0  75.0     10.00    m    1/81       ninguna
9           10 -0.134628     0.0  60.0      9.10    m  400/80       ninguna
10          11  2.178521     0.0  67.0      8.99   nb  100/89       ninguna
11          12  0.036717     NaN  97.0      7.46    h    1/89       ninguna
13          14  1.493144     NaN  75.0      9.10    h   25/85  hipertension
15          19 -0.477316     0.0  68.0      7.54    m  145/81       ninguna

    Edad (z)  Altura (z)
0  -0.734333    0.140642
1  -1.077022    1.828348
2   0.465078   -1.636565
3   1.321800    0.056433
4  -0.220300   -1.734587
5  -0.048956   -0.984495
6  -0.391644    0.328165
7  -1.248366    0.515688
8  -1.162694    1.467265
9  -0.134628   -0.225733
10  2.178521    0.590000
11  0.036717    0.328165
13  1.493144   -0.421927
15 -0.477316    0.338600
    Unnamed: 0      Edad  Altura  Peso  Promedio Sexo      LU  Observación   \
0            0 -0.734333     NaN  83.0      7.79    h  125/89       ninguna
1            1 -1.077022     NaN  86.0      9.70    h   35/88       ninguna
2            2  0.465078     NaN  50.0      7.10    m  142/80  hipertension
3            3  1.321800     NaN  70.0      6.54    m  553/83       ninguna
4            4 -0.220300     NaN  81.0      7.21    h  495/83  hipertension
5            5 -0.048956     NaN  93.0      7.10    h   25/78       ninguna
6            6 -0.391644     NaN  82.5      6.90    h  445/81       ninguna
7            7 -1.248366     NaN  86.3      8.43    h    5/84       ninguna
8            8 -1.162694     NaN  75.0     10.00    m    1/81       ninguna
9           10 -0.134628     NaN  60.0      9.10    m  400/80       ninguna
10          11  2.178521     0.0  67.0      8.99   nb  100/89       ninguna
11          12  0.036717     NaN  97.0      7.46    h    1/89       ninguna
13          14  1.493144     NaN  75.0      9.10    h   25/85  hipertension
15          19 -0.477316     NaN  68.0      7.54    m  145/81       ninguna

    Edad (z)  Altura (z)
0  -0.734333    0.140642
1  -1.077022    1.828348
2   0.465078   -1.636565
3   1.321800    0.056433
4  -0.220300   -1.734587
5  -0.048956   -0.984495
6  -0.391644    0.328165
7  -1.248366    0.515688
8  -1.162694    1.467265
9  -0.134628   -0.225733
10  2.178521    0.590000
11  0.036717    0.328165
13  1.493144   -0.421927
15 -0.477316    0.338600

<ipython-input-33-ea8ecf51cef2>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['Altura'][indice_h] = sp.stats.zscore(df_1['Altura'][indice_h])
<ipython-input-33-ea8ecf51cef2>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['Altura'][indice_m] = sp.stats.zscore(df_1['Altura'][indice_m])

Por supuesto, queda el problema de que hacer con el caso 'nb'.
Para eso podemos consultar una fuente separada de datos y hacer una modificacion ad-hoc.

In [31]:
df_1['Altura (z)'][10]= 0.59

<ipython-input-31-475f0505a820>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['Altura (z)'][10]= 0.59

Aunque (como notó un compañero en el foro) esta normalización muy posiblemente carezca de sentido. Hay evidentemente una dificultad al tener que elegir como normalizar los datos partiendo de información sobre género en una columna donde se recopilaba el sexo de los sujetos. Ante la información faltante, puede ser necesario identificar al sujeto como parte de uno de los dos grupos (si fuese posible) y sino, quizás no se pueda estandarizar los datos y convenga dejarlos así (entendiendo las consecuencias de hacerlo). 

Ahora podemos aplicar la normalizacion min-max al peso.

Notemos que para poder hacer esto necesitamos haber removido el outlier en el peso, de lo contrario, se arruina el procedimiento.

In [34]:
df_1['Peso (norm)'] = (df_1['Peso'] - df_1['Peso'].min())/(df_1['Peso'].max() - df_1['Peso'].min())

print(df_1)

    Unnamed: 0      Edad  Altura  Peso  Promedio Sexo      LU  Observación   \
0            0 -0.734333     NaN  83.0      7.79    h  125/89       ninguna
1            1 -1.077022     NaN  86.0      9.70    h   35/88       ninguna
2            2  0.465078     NaN  50.0      7.10    m  142/80  hipertension
3            3  1.321800     NaN  70.0      6.54    m  553/83       ninguna
4            4 -0.220300     NaN  81.0      7.21    h  495/83  hipertension
5            5 -0.048956     NaN  93.0      7.10    h   25/78       ninguna
6            6 -0.391644     NaN  82.5      6.90    h  445/81       ninguna
7            7 -1.248366     NaN  86.3      8.43    h    5/84       ninguna
8            8 -1.162694     NaN  75.0     10.00    m    1/81       ninguna
9           10 -0.134628     NaN  60.0      9.10    m  400/80       ninguna
10          11  2.178521     0.0  67.0      8.99   nb  100/89       ninguna
11          12  0.036717     NaN  97.0      7.46    h    1/89       ninguna
13          14  1.493144     NaN  75.0      9.10    h   25/85  hipertension
15          19 -0.477316     NaN  68.0      7.54    m  145/81       ninguna

    Edad (z)  Altura (z)  Peso (norm)
0  -0.734333    0.140642     0.702128
1  -1.077022    1.828348     0.765957
2   0.465078   -1.636565     0.000000
3   1.321800    0.056433     0.425532
4  -0.220300   -1.734587     0.659574
5  -0.048956   -0.984495     0.914894
6  -0.391644    0.328165     0.691489
7  -1.248366    0.515688     0.772340
8  -1.162694    1.467265     0.531915
9  -0.134628   -0.225733     0.212766
10  2.178521    0.590000     0.361702
11  0.036717    0.328165     1.000000
13  1.493144   -0.421927     0.531915
15 -0.477316    0.338600     0.382979

Por último, puede que nos interesa calcular alguna normalización especial dependiendo de la aplicación. Quizás queremos comparar el promedio de los alumnos con su promedio histórico, y para eso simplemente lo restamos.

In [35]:
historico=8.23
df_1['Promedio (historico)'] = df_1['Promedio'] - historico
print(df_1)

    Unnamed: 0      Edad  Altura  Peso  Promedio Sexo      LU  Observación   \
0            0 -0.734333     NaN  83.0      7.79    h  125/89       ninguna
1            1 -1.077022     NaN  86.0      9.70    h   35/88       ninguna
2            2  0.465078     NaN  50.0      7.10    m  142/80  hipertension
3            3  1.321800     NaN  70.0      6.54    m  553/83       ninguna
4            4 -0.220300     NaN  81.0      7.21    h  495/83  hipertension
5            5 -0.048956     NaN  93.0      7.10    h   25/78       ninguna
6            6 -0.391644     NaN  82.5      6.90    h  445/81       ninguna
7            7 -1.248366     NaN  86.3      8.43    h    5/84       ninguna
8            8 -1.162694     NaN  75.0     10.00    m    1/81       ninguna
9           10 -0.134628     NaN  60.0      9.10    m  400/80       ninguna
10          11  2.178521     0.0  67.0      8.99   nb  100/89       ninguna
11          12  0.036717     NaN  97.0      7.46    h    1/89       ninguna
13          14  1.493144     NaN  75.0      9.10    h   25/85  hipertension
15          19 -0.477316     NaN  68.0      7.54    m  145/81       ninguna

    Edad (z)  Altura (z)  Peso (norm)  Promedio (historico)
0  -0.734333    0.140642     0.702128                 -0.44
1  -1.077022    1.828348     0.765957                  1.47
2   0.465078   -1.636565     0.000000                 -1.13
3   1.321800    0.056433     0.425532                 -1.69
4  -0.220300   -1.734587     0.659574                 -1.02
5  -0.048956   -0.984495     0.914894                 -1.13
6  -0.391644    0.328165     0.691489                 -1.33
7  -1.248366    0.515688     0.772340                  0.20
8  -1.162694    1.467265     0.531915                  1.77
9  -0.134628   -0.225733     0.212766                  0.87
10  2.178521    0.590000     0.361702                  0.76
11  0.036717    0.328165     1.000000                 -0.77
13  1.493144   -0.421927     0.531915                  0.87
15 -0.477316    0.338600     0.382979                 -0.69